# Generated by Django 5.0.4 on 2024-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='classe',
            old_name='nom',
            new_name='code',
        ),
        migrations.AddField(
            model_name='classe',
            name='libelle',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
