# Generated by Django 5.0.4 on 2024-05-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0002_rename_email_parent_email_mere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.parent'),
            preserve_default=False,
        ),
    ]
