# Generated by Django 5.0.4 on 2024-06-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proffeseur',
            new_name='Professeur',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='matricule',
            field=models.TextField(default='', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Personnel'), (2, 'Professeur'), (3, 'Parent_eleve')], null=True),
        ),
    ]
