# Generated by Django 5.0.4 on 2024-06-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notes', '0003_alter_note_enseignant'),
        ('gestion_utilisateur', '0003_rename_proffeseur_professeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignement',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.professeur'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(default='', editable=False, max_length=6),
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
    ]
