# Generated by Django 5.0.4 on 2024-04-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0003_eleve_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.classe'),
            preserve_default=False,
        ),
    ]
