# Generated by Django 5.0.4 on 2024-05-16 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0003_eleve_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='parent',
        ),
        migrations.AddField(
            model_name='parent',
            name='eleve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.eleve'),
            preserve_default=False,
        ),
    ]
