# Generated by Django 5.0.4 on 2024-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0004_eleve_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='annee_scolaire',
            field=models.ManyToManyField(to='gestion_utilisateur.annee_scolaire'),
        ),
    ]
