# Generated by Django 5.0.4 on 2024-05-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0005_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='coeficient',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
