# Generated by Django 5.0.4 on 2024-05-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0006_alter_matiere_coeficient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matiere',
        ),
    ]
