from gestion_utilisateur import views
from django.urls import path

urlpatterns = [
    path('dashboard',views.dashboard),
    path('dsh_enseignant',views.dsh_enseignant),
    path('create_anneescolaire', views.create_anneescolaire),
    path('show_anneescolaire', views.show_anneescolaire),
    path('create_notes', views.create_notes),
    path('show_notes', views.show_notes),
    path('create_Enseignement', views.create_Enseignement),
    path('show_enseignement', views.show_enseignement),
    path('filtrer_eleves/<int:id>', views.filtrer_eleves, name='filtrer_eleves'),
    path('create_parent', views.create_parent),
    path('show_parent', views.show_parent),
    path('create_matiere', views.create_matiere),
    path('show_matiere', views.show_matiere),
    path('create_classe', views.create_classe),
    path('show_classe', views.show_classe),
    path('create_personnelAD', views.create_personnelAD),
    path('show_personnelAD', views.show_personnelAD),
    path('create_Enseignant', views.create_Enseignant),
    path('show_enseignant', views.show_enseignant),
    path('create_Eleve', views.create_Eleve),
    path('show_eleve', views.show_eleve),
    path('create_Poste', views.create_Poste),
    path('show_poste', views.show_poste),
    path('login_user', views.login_user),
    path('log_out', views.log_out),
    path('register_user', views.register_user),
    path('', views.login_view , name='account/login/'),
    path('pwd_oublier', views.pwd_oublier),
    path('change_password', views.change_password),
    path('modifier', views.modifier),
    path('modifier/<int:id>', views.modifier, name="modifier"),
    path('update_poste/<int:id>', views.update_poste, name="update_poste"),
    path('modifierpersonnel/<int:id>', views.modifierpersonnel, name="modifierpersonnel"),
    path('update_personnel/<int:id>', views.update_personnel, name="update_personnel"),
    path('modifierclasse/<int:id>', views.modifierclasse, name="modifierclasse"),
    path('update_classe/<int:id>', views.update_classe, name="update_classe"),
    path('modifiermatiere/<int:id>', views.modifiermatiere, name="modifiermatiere"),
    path('update_matiere/<int:id>', views.update_matiere, name="update_matiere"),
    path('modifierannee/<int:id>', views.modifierannee, name="modifierannee"),
    path('update_annee/<int:id>', views.update_annee, name="update_annee"),
    path('modifierenseignant/<int:id>', views.modifierenseignant, name="modifierenseignant"),
    path('update_enseignant/<int:id>', views.update_enseignant, name="update_enseignant"),
    path('update_eleve/<int:id>', views.update_eleve, name="update_eleve"),
    path('delete_annee/<int:id>', views.delete_annee, name="delete_annee"),
    path('delete_enseignement/<int:id>/<int:enseignant_id>/', views.delete_enseignement, name='delete_enseignement'),
    path('delete_eleve/<int:id>', views.delete_eleve, name="delete_eleve"),
    path('delete_enseignant/<int:id>', views.delete_enseignant, name="delete_enseignant"),
    path('delete_classe/<int:id>', views.delete_classe, name="delete_classe"),
    path('delete_matiere/<int:id>', views.delete_matiere, name="delete_matiere"),
    path('search_enseignant', views.search_enseignant),
    path('search_annee', views.search_annee),
    path('search_eleve', views.search_eleve),
    path('detail/<int:id>', views.detail),
    path('affecter/<int:id>', views.affecter), 
    path('affecter_notes', views.affecter_notes),
    path('get_matiere_for_classe/<int:classe_id>/', views.get_matiere_for_classe, name='get_matiere_for_classe'),
    path('get_coeficient_for_classe/<int:classe_id>/', views.get_coeficient_for_classe, name='get_coeficient_for_classe'),
    path('save_notes/', views.save_notes, name='save_notes'),

] 