# Generated by Django 5.0.4 on 2024-05-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notes', '0001_initial'),
        ('gestion_utilisateur', '0007_delete_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.classe'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='coeficient',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='libelle',
            field=models.CharField(max_length=255),
        ),
    ]
