# Generated by Django 5.0.4 on 2024-06-07 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_notes', '0001_initial'),
        ('gestion_utilisateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gestion_utilisateur.classe'),
        ),
        migrations.AddField(
            model_name='note',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gestion_utilisateur.eleve'),
        ),
        migrations.AddField(
            model_name='note',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gestion_utilisateur.enseignant'),
        ),
        migrations.AddField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gestion_notes.matiere'),
        ),
        migrations.AddField(
            model_name='notehistory',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notehistory',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='gestion_notes.note'),
        ),
    ]
