# Generated by Django 5.0.4 on 2024-06-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notes', '0002_initial'),
        ('gestion_utilisateur', '0003_rename_proffeseur_professeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gestion_utilisateur.professeur'),
        ),
    ]
